### ISSUE TITLE
Following docs for Existing project migration results in exception

### ISSUE THREAD

**Issue by AlexanderWells-diamond** [dls-controls/dls-python3-skeleton#37]
When following the instructions found on this page: https://dls-controls.github.io/dls-python3-skeleton/master/how-to/existing.html

Specifically the line `dls-python3-skeleton existing .`, I saw this error:

```
[pts_webserver]$ dls-python3-skeleton existing .
Traceback (most recent call last):
  File "/dls_sw/prod/tools/RHEL7-x86_64/defaults/bin/dls-python3-skeleton", line 11, in <module>
    sys.exit(main())
  File "/dls_sw/prod/python3/RHEL7-x86_64/dls-python3-skeleton/1.4/prefix/lib/python3.7/site-packages/dls_python3_skeleton/__main__.py", line 200, in main
    args.func(args)
  File "/dls_sw/prod/python3/RHEL7-x86_64/dls-python3-skeleton/1.4/prefix/lib/python3.7/site-packages/dls_python3_skeleton/__main__.py", line 156, in existing
    package = validate_package(args)
  File "/dls_sw/prod/python3/RHEL7-x86_64/dls-python3-skeleton/1.4/prefix/lib/python3.7/site-packages/dls_python3_skeleton/__main__.py", line 126, in validate_package
    assert valid, f"'{package}' is not a valid python package name"
AssertionError: '' is not a valid python package name
```

Providing the full path (`~/dev/pts_webserver/` instead of `.`) seemed to resolve the problem.

**Comment by gilesknap** [comment]
I can reproduce this. It must me a new bug.
